version: '3'

services:
  app:
    container_name: gatsby-tf-app
    build: ./docker
    env_file: .env.development
    volumes:
      - ./:/src
      - /var/www/data/yarn/cache:/usr/local/share/.cache/yarn:cached
      - /var/www/data/npm:/root/.npm:cached
    working_dir: /src
    ports:
      - "5000:80"