version: '3'

services:
  app:
    container_name: gatsby-tf-app
    build: 
      context: .
      dockerfile: docker/Dockerfile
    env_file: .env.development
    volumes:
      - ./:/app
      - /var/www/data/yarn/cache:/usr/local/share/.cache/yarn:cached
      - /var/www/data/npm:/root/.npm:cached
    working_dir: /app
    ports:
      - "8000:8000"
      - "9929:9929"
      - "9230:9230"